# Makefile to build, run, and plot the code
JSONCPP_INCLUDE_DIR = /usr/include/jsoncpp
JSONCPP_LIB_DIR = /usr/lib

build:
	g++ -o client client.cpp 
	g++ -o server server.cpp

run:
	python3 demoo.py

plot:
	python3 plotcount.py